#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# init conda
source ~/miniconda3/bin/activate
conda init --all

# install vscode extension
if command -v code &> /dev/null; then
    echo "Installing VSCode extensions"
    code --install-extension alexlu07.vscode-pathfinder
else
    echo "VSCode is not installed, skipping extension installation."
fi
