#!/usr/bin/env bash

set -euo pipefail

# ghostty
if ! command -v ghostty >/dev/null 2>&1; then
    echo "Installing Ghostty"

#====== LINUX ======
    sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)" > /dev/null
#====== MAC ======
    open "https://ghostty.org/download"

    echo
    read -r -p "Press Enter after Ghostty is installed to continue..."
#====== END ======
else
    echo "Ghostty is already installed"
fi

#====== MAC ======
# brew
if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    NONINTERACTIVE=1 /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "Installed Homebrew successfully"
else
    echo "Homebrew is already installed"
fi
#====== END ======

# zsh
if ! command -v zsh >/dev/null 2>&1; then
    echo "Installing zsh"

#====== LINUX ======
    sudo apt install zsh >/dev/null
#====== MAC ======
    brew install zsh >/dev/null
#====== END ======

    echo "Installed zsh sucessfully"
else
    echo "zsh is already installed"
fi

# oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing Oh My Zsh"
    RUNZSH=no CHSH=yes KEEP_ZSHRC=no sh -c \
    "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    >/dev/null
    echo "Installed Oh My Zsh successfully"
else
    echo "Oh My Zsh is already installed"
fi

# fzf
if ! command -v fzf >/dev/null 2>&1; then
    echo "Installing fzf"

#====== LINUX ======
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --all >/dev/null
#====== MAC ======
    brew install fzf >/dev/null
#====== END ======

    echo "Installed fzf sucessfully"
else
    echo "fzf is already installed"
fi

#====== MAC ======
# reattach-to-user-namespace for tmux clipboard
if ! command -v reattach-to-user-namespace >/dev/null 2>&1; then
    echo "Installing reattach-to-user-namespace"
    brew install reattach-to-user-namespace >/dev/null
    echo "Installed reattach-to-user-namespace sucessfully"
else
    echo "reattach-to-user-namespace is already installed"
fi
#====== END ======

# Zellij
if ! command -v zellij >/dev/null 2>&1; then
    echo "Installing Zellij"

#====== LINUX ======
    sudo snap install zellij --classic >/dev/null
#====== MAC ======
    brew install zellij >/dev/null
#====== END ======

    echo "Installed Zellij sucessfully"
else
    echo "Zellij is already installed"
fi

# tmux
if ! command -v tmux >/dev/null 2>&1; then
    echo "Installing tmux"

#====== LINUX ======
    sudo apt install tmux >/dev/null
#====== MAC ======
    brew install tmux >/dev/null
#====== END ======

    echo "Installed tmux sucessfully"
else
    echo "tmux is already installed"
fi

#conda
if ! command -v conda >/dev/null 2>&1; then
    echo "Installing Miniconda3"
    mkdir -p ~/miniconda3

#====== LINUX ======
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh -q
#====== MAC ======
    curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
#====== END ======

    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
    rm ~/miniconda3/miniconda.sh
    echo "Installed Miniconda3 sucessfully"
else
    echo "Miniconda3 is already installed"
fi
