" Install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
  Plug 'ojroques/vim-oscyank'
call plug#end()

" Auto-install missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif

" OSCYank on + register
autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '+' | execute 'OSCYankRegister +' | endif

syntax on

set number
set relativenumber

set tabstop=4
set shiftwidth=4
set softtabstop=-1
set expandtab

set autoindent
set smarttab

nnoremap <C-j> 3jzz
nnoremap <C-k> 3kzz

